// src/components/Contact.jsx
export default function Contact() {
  return (
    <section id="contact" className="py-24 px-6">
      <div className="max-w-2xl mx-auto text-center">
        <h2 className="sr-only">Get in Touch</h2>
        <p className="text-xl leading-relaxed text-gray-800 mb-12">
          If AI is on your mind and you're not sure where to start, that's
          exactly the conversation I'm here for.
        </p>
        <div className="flex flex-col md:flex-row gap-4 justify-center items-center">
          <a
            href="mailto:al@getitworking.ai?subject=AI%20for%20my%20business"
            className="inline-block bg-amber-700 hover:bg-amber-800 text-white font-semibold py-3 px-6 rounded-lg transition-colors focus:outline-none focus:ring-2 focus:ring-amber-700 focus:ring-offset-2 w-full md:w-auto text-center"
          >
            Email me
          </a>
          <a
            href="https://www.linkedin.com/in/albrayne/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-gray-600 underline hover:text-gray-800 transition-colors w-full md:w-auto text-center"
          >
            Or message me on LinkedIn
          </a>
        </div>
      </div>
    </section>
  )
}

// src/components/Contact.vue
<script setup>
import Button from 'primevue/button'
</script>

<template>
  <section id="contact" class="bg-surface-50 px-6 py-20 md:px-12 lg:px-20">
    <div class="max-w-3xl mx-auto text-center flex flex-col items-center gap-4">
      <h2 class="text-surface-900 font-bold text-4xl leading-tight">
        If AI is on your mind and you're not sure where to start, that's exactly the conversation I'm here for.
      </h2>
      <div class="flex flex-col md:flex-row items-center gap-4 mt-8">
        <Button
          label="Email me"
          icon="pi pi-envelope"
          rounded
          @click="() => window.location.href = 'mailto:al@getitworking.ai?subject=AI%20for%20my%20business'"
        />
      </div>
      <div class="flex flex-col md:flex-row items-center gap-4 mt-2">
        <a
          href="https://www.linkedin.com/in/albrayne/"
          target="_blank"
          rel="noopener noreferrer"
          class="text-primary font-medium hover:underline ml-4"
        >
          Or message me on LinkedIn
        </a>
      </div>
    </div>
  </section>
</template>
