// src/components/Header.vue
<script setup>
import { ref, onMounted, onUnmounted } from 'vue'
import Button from 'primevue/button'

const scrolled = ref(false)
const handleScroll = () => { scrolled.value = window.scrollY > 50 }

onMounted(() => window.addEventListener('scroll', handleScroll, { passive: true }))
onUnmounted(() => window.removeEventListener('scroll', handleScroll))

const handleCTAClick = () => {
  document.getElementById('contact')?.scrollIntoView({ behavior: 'smooth' })
}
</script>

<template>
  <header :class="['fixed top-0 left-0 right-0 z-50 transition-all duration-300', scrolled ? 'bg-white/95 border-b border-gray-100 shadow-sm' : 'bg-transparent']">
    <div class="max-w-6xl mx-auto px-6 py-4 flex justify-between items-center">
      <span :class="['text-xl font-semibold transition-colors duration-300', scrolled ? 'text-surface-900' : 'text-white']">GetItWorking.ai</span>
      <Button label="Let's talk" rounded @click="handleCTAClick" />
    </div>
  </header>
</template>

// src/components/Header.jsx
import { useState, useEffect } from 'react'

export default function Header() {
  const [scrolled, setScrolled] = useState(false)

  useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 50)
    window.addEventListener('scroll', handleScroll, { passive: true })
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  const handleCTAClick = () => {
    const contactSection = document.getElementById('contact');
    if (contactSection) {
      contactSection.scrollIntoView({ behavior: 'smooth' });
    }
  };

  return (
    <header className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${scrolled ? 'bg-white/95 border-b border-gray-100 shadow-sm' : 'bg-transparent'}`}>
      <div className="max-w-6xl mx-auto px-6 py-4 flex justify-between items-center">
        <span className="text-xl font-semibold">getitworking.ai</span>
        <button
          onClick={handleCTAClick}
          className="bg-amber-700 hover:bg-amber-800 text-white font-semibold py-2 px-5 rounded-lg transition-colors focus:outline-none focus:ring-2 focus:ring-amber-700 focus:ring-offset-2"
        >
          Let's talk
        </button>
      </div>
    </header>
  )
}
