// src/components/Partners.jsx
export default function Partners() {
  return (
    <section id="partners" className="py-20 px-6">
      <div className="max-w-4xl mx-auto text-center">
        <h2 className="text-2xl md:text-3xl font-bold mb-8">Working with</h2>
        <p className="text-lg leading-relaxed text-gray-800">
          I have, in my network, experienced development and business partners
          who extend what I can deliver. When your project needs a bigger
          production team or broader strategic input, the right people are
          already in the conversation.
        </p>
      </div>
    </section>
  )
}

// src/components/Partners.vue
<template>
  <section id="partners" class="bg-primary px-6 py-20 md:px-12 lg:px-20">
    <div class="max-w-6xl mx-auto">
      <div class="flex flex-col gap-12">
        <div class="flex flex-col gap-4 items-center text-center">
          <h2 class="text-primary-contrast text-4xl font-bold leading-tight">Partners</h2>
          <p class="text-primary-contrast/75 text-lg leading-tight text-center max-w-3xl">
            I have, in my network, experienced development and business partners who extend what I can deliver.
            When your project needs a bigger production team or broader strategic input, the right people are already in the conversation.
          </p>
        </div>

<!--        <div class="grid grid-cols-1 md:grid-cols-3 gap-4 gap-y-10">-->
<!--          <div class="flex items-center justify-center gap-4 min-h-20">-->
<!--            <i class="pi pi-building text-primary-contrast text-3xl" />-->
<!--            <div class="text-primary-contrast text-xl font-semibold leading-tight">Development</div>-->
<!--          </div>-->
<!--          <div class="flex items-center justify-center gap-4 min-h-20">-->
<!--            <i class="pi pi-code text-primary-contrast text-3xl" />-->
<!--            <div class="text-primary-contrast text-xl font-semibold leading-tight">Engineering</div>-->
<!--          </div>-->
<!--          <div class="flex items-center justify-center gap-4 min-h-20">-->
<!--            <i class="pi pi-briefcase text-primary-contrast text-3xl" />-->
<!--            <div class="text-primary-contrast text-xl font-semibold leading-tight">Strategy</div>-->
<!--          </div>-->
<!--        </div>-->
      </div>
    </div>
  </section>
</template>
