// src/components/ProblemSection.jsx
export default function ProblemSection() {
  return (
    <section id="problem" className="py-16 md:py-24 px-6">
      <div className="max-w-3xl mx-auto">
        <h2 className="sr-only">The Challenge</h2>
        <p className="text-lg leading-relaxed mb-6">
          You've used ChatGPT. You've heard of Claude. You've seen posts where devs create entire products in a weekend sprint. You can feel the ground shifting.
        </p>
        <p className="text-lg leading-relaxed mb-8">
          It's hard to know what to do in this landscape. Hard to write a brief when the technology moves faster than your understanding of it. Hard to tell who to trust when everyone bolted "AI" onto their services page six months ago.
        </p>
        <p className="text-lg leading-relaxed mt-12">
          Doing nothing feels increasingly risky.
        </p>
      </div>
    </section>
  )
}

// src/components/ProblemSection.vue
<template>
  <section id="problem" class="bg-surface-50 px-6 md:px-12 lg:px-20 py-20">
    <div class="max-w-6xl mx-auto">
      <h2 class="sr-only">The Challenge</h2>

      <!-- Icon row -->
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4 text-center mb-12">
        <div class="w-full p-4">
          <i class="pi pi-comment text-primary" style="font-size: 3rem;"></i>
          <div class="text-surface-900 text-xl font-medium leading-tight mt-4">
            You've used ChatGPT
          </div>
        </div>
        <div class="w-full p-4">
          <i class="pi pi-sparkles text-primary" style="font-size: 3rem;"></i>
          <div class="text-surface-900 text-xl font-medium leading-tight mt-4">
            You've heard of Claude
          </div>
        </div>
        <div class="w-full p-4">
          <i class="pi pi-bolt text-primary" style="font-size: 3rem;"></i>
          <div class="text-surface-900 text-xl font-medium leading-tight mt-4">
            You've seen posts where devs create entire products in a weekend sprint
          </div>
        </div>
      </div>

      <!-- Salient callout 1 -->
      <div class="max-w-3xl mx-auto text-center py-8">
        <p class="text-3xl md:text-4xl font-bold text-surface-900 leading-snug">
          You can feel the ground shifting.
        </p>
      </div>

      <!-- Prose -->
      <p class="text-lg text-surface-600 leading-relaxed max-w-3xl mx-auto text-center">
        It's hard to know what to do in this landscape. Hard to write a brief when the technology moves faster than your understanding of it. Hard to tell who to trust when everyone bolted "AI" onto their services page six months ago.
      </p>

      <!-- Salient callout 2 -->
      <div class="max-w-3xl mx-auto text-center py-8">
        <p class="text-3xl md:text-4xl font-bold text-surface-900 leading-snug">
          Doing nothing feels increasingly risky.
        </p>
      </div>
    </div>
  </section>
</template>
