// src/App.jsx
import Header from './components/Header'
import Hero from './components/Hero'
import ProblemSection from './components/ProblemSection'
import WhatWeDo from './components/WhatWeDo'
import About from './components/About'
import Partners from './components/Partners'
import Contact from './components/Contact'
import Footer from './components/Footer'

const SHOW_PARTNERS = true

export default function App() {
  return (
    <>
      <Header />
      <main>
        <Hero />
        <ProblemSection />
        <WhatWeDo />
        <About />
        {SHOW_PARTNERS && <Partners />}
        <Contact />
      </main>
      <Footer />
    </>
  )
}

// src/App.vue
<script setup>
import Header from './components/Header.vue'
import Hero from './components/Hero.vue'
import ProblemSection from './components/ProblemSection.vue'
import WhatWeDo from './components/WhatWeDo.vue'
import About from './components/About.vue'
import Partners from './components/Partners.vue'
import Contact from './components/Contact.vue'
import Footer from './components/Footer.vue'

const SHOW_PARTNERS = true
</script>

<template>
  <Header />
  <main>
    <Hero />
    <ProblemSection />
    <WhatWeDo />
    <About />
    <Partners v-if="SHOW_PARTNERS" />
    <Contact />
  </main>
  <Footer />
</template>
